# Generated by Django 3.1.7 on 2021-06-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
